// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myzacfokkhrkstavmdzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15emFjZm9ra2hya3N0YXZtZHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjI4MDIsImV4cCI6MjA3MjI5ODgwMn0.mZ3TiGM9Ip5801K2A295HZWUeuBY0Z_ibvRdxx_qNFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});